### ISSUE TITLE
Cannot find library opae-proxy required for OPAE/OPAE

### ISSUE THREAD

**Issue by gbhure** [OPAE/opae-sdk#1355] opened 2019-10-24 05:40 UTC
Hi,
I'm facing issues while building PSME. Below is the error.
`Cannot find library opae-proxy required for OPAE/OPAE`
I have followed below steps to build

```
git clone https://github.com/intel/intelRSD.git
cd intelRSD/PSME/third_party
# ./download.sh
cd ..
mkdir build.release
cd build.release
cmake ..
```
Anybody facing similar issues? Can someone please help me to get my build proceed further.

**Comment by tswhison** [comment] 2019-10-31 16:39
Closing - seems to be a duplicate of https://github.com/intel/intelRSD/issues/110.  Please follow up with the RSD project.

**Closed by tswhison** 2019-10-31 16:39 UTC
